### ISSUE TITLE
Android not compiling (lib 1.4.0)

### ISSUE THREAD

**Issue by fabriziomoscon** [tipsi/tipsi-stripe#20]
`lib version 1.4.0` (I am not sure if this bug affects also version 2.0.0)
`react-native 0.38.0`

JAVA version
```bash
/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "1.8.0_121"
```
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

```bash
:app:dexDevDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexIndexOverflowException: Cannot merge new index 66024 into a non-jumbo instruction!
Unknown source file : 	at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
Unknown source file : 	at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
Unknown source file : 	at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
Unknown source file : 	at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
Unknown source file : 	at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
Unknown source file : 	at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
Unknown source file : 	at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
Unknown source file : 	at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
Unknown source file : 	at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
Unknown source file : 	at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDevDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDevDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

It seems related to this https://developer.android.com/studio/build/multidex.html

adding `multiDexEnabled true` fixes the problem but maybe there are ways to reduce the number of methods that this library imports

```
android {
    defaultConfig {
        ...
        minSdkVersion 21 
        targetSdkVersion 25
        multiDexEnabled true
    }
    ...
}
```

UPDATE

maybe upgrading the latest `stripe-android` dependency could reduce the load:
https://github.com/stripe/stripe-android/blob/master/CHANGELOG#L14

**Comment by isnifer** [comment]
@fabriziomoscon I'm not an expert, but I had a similar problem with another project, next command helped me:
```sh
cd android && ./gradlew clean
```
After that everything compiled as expected.

**Comment by cybergrind** [comment]
Assume that problem was solved
