### ISSUE TITLE
Android Pay crashes the application

### ISSUE THREAD

**Issue by Progoogler** [tipsi/tipsi-stripe#258]
I can go so far as "Unlock to pay with Android Pay" where I enter my phone's unlock key. Then immediately after I enter the key, the application crashes with the following error:
```
FATAL EXCEPTION main:                                                         
Process: com.link, PID: 14772
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100502, result=-1, data=Intent { (has extras) }} to activity {com.link/com.link.MainActivity}: com.facebook.react.bridge.NoSuchKeyException: quantity
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4717)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4760)
    at android.app.ActivityThread.access$1500(ActivityThread.java:197)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1736)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6897)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
  Caused by: com.facebook.react.bridge.NoSuchKeyException: quantity
    at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:129)
    at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:169)
    at com.gettipsi.stripe.StripeModule.handleLoadMascedWaletRequest(StripeModule.java:559)
    at com.gettipsi.stripe.StripeModule.access$100(StripeModule.java:71)
    at com.gettipsi.stripe.StripeModule$1.onActivityResult(StripeModule.java:125)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:255)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:706)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:126)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
    at android.app.Activity.dispatchActivityResult(Activity.java:6808)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4713)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4760) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:197) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1736) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:145) 
    at android.app.ActivityThread.main(ActivityThread.java:6897) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
``` 
```
Has anyone else experienced a similar issue? I am able to process a test payment with the Credit Card Payment Form so it's not my server that's the problem. Any wild guesses as to what may be causing this crash?

Here's how my payment process function looks:

```
  handleAndroidPayPress = () => {
    if (!this.state.androidPayAllowed) {
      this.props.displayMessage('Your device does not support Android Pay', 'Consider using another form of payment');
      return;
    }

    NetInfo.isConnected.fetch()
    .then( async isConnected => {
      if (isConnected) {
        try {
          const token = await stripe.paymentRequestWithAndroidPay({
            total_price: this.getStringAmount(),
            currency_code: 'USD',
            line_items: [{
              currency_code: 'USD',
              description: this.description,
              total_price: this.getStringAmount(),
            }],
          });
          if (token && token.tokenId) {
            fetch('http://ec2-35-173-231-24.compute-1.amazonaws.com/charge', {
              method: 'POST',
              body: JSON.stringify(token),
              headers: new Headers({
                'Content-Type': 'application/json'
              })
            }).then(res => {
              console.log('Server Response:', res);
              if (res.ok && res._bodyInit !== 'Failed') {
                // Payment success!
              } else {
                // Display error Message..
              }
            });
          }
        } catch (error) {
          // Error:(
        }
      }
    });
  }
```

**Comment by Progoogler** [comment]
Sorry, the cause of the error was so obvious. I simply was missing a `"quantity"` property in `line_items`.
