### ISSUE TITLE
[Experimental - 8.0.0-beta.4] Firebase auth not working with experimental tipsi-stripe on Android

### ISSUE THREAD

**Issue by Shaita-KrZ** [tipsi/tipsi-stripe#538]
## Before I have submitted the issue 
[+] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[+] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[+] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[+] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I've successfully built my project with latest tipsi-stripe library on Android. 
However, when trying to call any firebase auth methods like signInWithEmailAndPassword nothing is returned from firebase. If I remove tipsi-stripe, everything is working. 

I believe this issue might be related to this error (I'm getting from android logcat when starting the app): 

`E/GoogleApiManager: Failed to get service from broker. 
    java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:274)
        at java.util.jar.JarVerifier.update(JarVerifier.java:229)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:374)
        at java.util.jar.JarFile.getInputStream(JarFile.java:441)
        at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:177)
        at java.net.URL.openStream(URL.java:1058)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:989)
        at java.lang.Class.getResourceAsStream(Class.java:2211)
        at com.google.android.gms.common.internal.LibraryVersion.getVersion(Unknown Source:11)
        at com.google.firebase.auth.api.internal.zzeg.zzcc(Unknown Source:7)
        at com.google.firebase.auth.api.internal.zzeg.zzek(Unknown Source:6)
        at com.google.firebase.auth.api.internal.zzdo.getGetServiceRequestExtraArgs(Unknown Source:30)
        at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source:208)
        at com.google.android.gms.common.api.internal.zabo.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source:8)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

If any of you guys have an idea, it would help a lot.

## Environment
* `tipsi-stripe` version: 8.0.0-beta.4
* React-Native version: 0.59.8
* (Android only) `com.google.firebase:firebase-core` version: 16.0.9
* (Android only) `com.google.android.gms:play-services-base` version: 16.1.0

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 28
* android.buildToolsVersion 28.0.3
* android.defaultConfig.targetSdkVersion 26
* android.defaultConfig.multiDexEnabled (if exists) true

## Screenshots, GIFs (Must to have)
<img width="1091" alt="Screen Shot 2019-09-10 at 5 54 39 PM" src="https://user-images.githubusercontent.com/11573982/64629763-18056b00-d3f4-11e9-8b24-7c46a98db63b.png">

**Comment by n-sviridenko** [comment]
Same issue for me. Expo AV fails to download video streams:

```log
E/ExperienceActivityUtils: java.lang.StringIndexOutOfBoundsException: length=0; index=0
D/Event: No subscribers registered for event class host.exp.exponent.experience.ReactNativeActivity$ExperienceDoneLoadingEvent
    No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
E/LoadTask: Unexpected exception loading stream
    java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:274)
        at java.util.jar.JarVerifier.update(JarVerifier.java:229)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:393)
        at java.util.jar.JarFile.getInputStream(JarFile.java:460)
        at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
        at java.net.URL.openStream(URL.java:1072)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:989)
        at java.lang.Class.getResourceAsStream(Class.java:2215)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheList(PublicSuffixDatabase.java:313)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheListUninterruptibly(PublicSuffixDatabase.java:292)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.java:112)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.java:85)
        at okhttp3.Cookie.parse(Cookie.java:311)
        at okhttp3.Cookie.parse(Cookie.java:219)
        at okhttp3.Cookie.parseAll(Cookie.java:445)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:315)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:160)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
I/ExoPlayerImpl: Release feb564f [ExoPlayerLib/2.9.2] [generic_x86, Android SDK built for x86, Google, 29] [goog.exo.core, goog.exo.okhttp]
V/FA: Inactivity, disconnecting from the service
```

Version: `tipsi/tipsi-stripe#2edbd84f1e4caf51649c694e91a1cd90740c7364`

(More here: https://github.com/expo/expo/issues/8209#issuecomment-625740112)
