### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [tipsi/tipsi-stripe#756]
Hi, 

this issue is not so much related to thi slibrary however this library is stright port from yours (https://github.com/jonasbark/flutter_stripe_payment/issues/271).. and author of that library is not  answering at all. So i would like to ask maybe you will know what is happening.

so my code is
```
Token token = await StripePayment.paymentRequestWithNativePay(
        androidPayOptions: AndroidPayPaymentRequest(
          totalPrice: "100",
          currencyCode: "GBP",
        ),
        applePayOptions: ApplePayPaymentOptions(
          countryCode: "GBP",
          currencyCode: "UK",
          items: [
            ApplePayItem(
              label: "some label",
              amount: "100",
            )
          ],
        ));
```

i get this error:

```
E/flutter (25286): 	at com.gettipsi.stripe.PayFlow.getEnvironment(PayFlow.java:44)
E/flutter (25286): 	at com.gettipsi.stripe.GoogleApiPayFlowImpl.createPaymentsClient(GoogleApiPayFlowImpl.java:64)
E/flutter (25286): 	at com.gettipsi.stripe.GoogleApiPayFlowImpl.isReadyToPay(GoogleApiPayFlowImpl.java:77)
E/flutter (25286): 	at com.gettipsi.stripe.GoogleApiPayFlowImpl.deviceSupportsAndroidPay(GoogleApiPayFlowImpl.java:218)
E/flutter (25286): 	at com.gettipsi.stripe.StripeModule.deviceSupportsAndroidPay(StripeModule.java:132)
E/flutter (25286): 	at de.jonasbark.stripepayment.StripePaymentPlugin.onMethodCall(StripePaymentPlugin.kt:23)
E/flutter (25286): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (25286): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (25286): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (25286): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25286): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (25286): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (25286): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (25286): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25286): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (25286): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

If you think you cannot help and have no idea why this may happen - feel free to close this issue. hoewever I am a bit deperate and any help would be appriciated :)

Cheers

**Comment by vytautas-pranskunas-** [comment]
Solved it: you have to provide androidPayMode in StripeOptions
